# std libs
import os

# third party libs
import yaml
import pandas as pd

# custom libs
from sql_tools import write_to_database


# constant variables
FILENAME = os.path.join(os.getcwd(), 'creds.yaml')
FINAL_COLS = ['year', 'month', 'zipcode', 'p1_category', \
           'temperature_min', 'temperature_max', 'relative_humidity_mean']

# defining dtypes

METEO_TYPES = {'temperature':'float64','relative_humidity':'float64',
               'precipitation_rate':'float64','wind_speed':'float64',
               'zipcode':'str'}
CONTRACT_TYPES = {'CONTRACT_ID':'int64','CLIENT_TYPE_ID':'int64',
                   'AVG_EUROS_IMPORT':'float64','POWER_P1':'float64',
                   'HAS_GAS':'boolean','HAS_SOLAR':'boolean','ZIPCODE':'str'}
ZIPCODE_TYPES = {'ZIPCODE':'str','ZC_LATITUDE':'float64',
                 'ZC_LONGITUDE':'float64','AUTONOMOUS_COMMUNITY':'str',
                 'AUTONOMOUS_COMMUNITY_NK':'str','PROVINCE':'str'}

# accessing DB credentials
with open(FILENAME, "r") as file:
    creds = yaml.safe_load(file)
    
# helpers
# defining filtering condition function that will be used to store only relevant meteo records in memory
def _filter_data_isin(table: str, column: str, lookup: list):
    '''
    Arg:
        table -> table you want to filter
        column -> table column as input for the lookup
        lookup -> list or any iterable that contains lookup values
    '''
    return table[table[column].isin(lookup)]

# defining a function to categorize p1_power column
def _category_p(power: float) -> str:
    if power >= 5000:
        return 'Over 5 MW'
    elif power < 3000:
        return 'Under 3 MW'
    else:
        return 'Between 3 and 5 MW'


# creating dataframes from csv files skipping the meteo one for now
df_contracts = pd.read_csv('contracts_eae.csv', dtype=CONTRACT_TYPES)
df_zipcode = pd.read_csv('zipcode_eae_v2.csv', dtype=ZIPCODE_TYPES)

# normalizing column names in lowercase
df_contracts.columns = df_contracts.columns.str.lower()
df_zipcode.columns = df_zipcode.columns.str.lower()

# listing all zipcodes with more than 10 contracts
zipcode_grouped = df_contracts.groupby('zipcode')['contract_id'].count()
zipcode_top = list(zipcode_grouped[zipcode_grouped > 10].index)

# fetching filtered df for meteo
# for each record in meteo we will check if the zipcode is among the top 10 before appending them to a dataframe
# the following line does not really populate the df
# the chunksize argument transforms it into an iterator that loads once it is processed
chunks = pd.read_csv('meteo_eae.csv', chunksize = 100000, \
                        dtype = METEO_TYPES, parse_dates= ['date'])

# now we are processing the chunks and concatenating them only with filtered values
# all not necessary values are destroyed after the following line is processed
df_meteo_top_raw = pd.concat([_filter_data_isin(table=chunk, \
                            column='zipcode',lookup=zipcode_top) \
                            for chunk in chunks], ignore_index=True)

# creating p1 category as required
df_contracts['p1_category'] = df_contracts['power_p1'].apply(lambda x: _category_p(x))

# filtering out client type 0
df_contracts_zero_raw = df_contracts[df_contracts['client_type_id']==0]

# removing unnecessary columns befor creating the joint table
df_contracts_zero = df_contracts_zero_raw[['p1_category','zipcode','has_solar','has_solar']]
df_meteo_top = df_meteo_top_raw[['date','temperature','relative_humidity','zipcode']]

# performing the required join
df_solar_indicators_raw = df_contracts_zero.merge(df_meteo_top, how='right', \
                                                            left_on='zipcode', right_on='zipcode')

# adding required columns of month and year and removing the date
df_solar_indicators_raw['year'] = df_solar_indicators_raw['date'].dt.strftime("%Y")
df_solar_indicators_raw['month'] = df_solar_indicators_raw['date'].dt.strftime("%B")
df_solar_indicators_raw = df_solar_indicators_raw.drop(columns='date')

# performing the groupby
df_solar_indicators_raw = df_solar_indicators_raw.groupby(['year','month','zipcode','p1_category','has_solar']).agg( \
                                {'temperature':['min', 'max'],'relative_humidity':'mean'} \
                                ).reset_index()

# flattening the multi_index generated by the groupby
df_solar_indicators_raw.columns = ['_'.join(col).strip('_') for col in df_solar_indicators_raw.columns]

# finalizing the dataframes by solar/nosolar contracts for sql loading
solar_indicators_with_solar = df_solar_indicators_raw[df_solar_indicators_raw['has_solar']==True][FINAL_COLS]
solar_indicators_no_solar = df_solar_indicators_raw[df_solar_indicators_raw['has_solar']==False][FINAL_COLS]
